### ISSUE TITLE
Problem in editing new code in details form

### ISSUE THREAD

**Issue by nikintan** [UmmiIzzati/Agile-in-GitHub#2]
@UmmiIzzati  I want add some details value in details form files. 
 i think we need to add the phone no, address and marital status in the details.

**Comment by UmmiIzzati** [comment]
owh. Okay. This is my suggestion.

ad this code to your file.

* <input type ="radio" name="maritalStatus" value="married" > Married <br>
 <input type="radio" name ="maritalStatus" value="single" > Single

 <input type="text" name="addres" > Address : *
